#!/bin/bash
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH
ls -lR /dev
mount -t proc proc /proc
date -s "2023-12-02 00:00:00"
mkfs.ext2 /dev/pmem1
mount -t tmpfs tmpfs /tmp
mkdir -p /tmp/mnt
mount /dev/pmem1 /tmp/mnt
cat /proc/mounts
tar --one-file-system -pcf - / | tar -C /tmp/mnt/ -xf -
umount /tmp/mnt
sync
