#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH
export DEBIAN_FRONTEND="noninteractive"
dpkg -i /mnt/machine-emulator-tools-v0.15.0.deb
date -s '2023-12-02 00:00:00'
cat > /usr/sbin/lambada-preinit << EOF
#!/bin/sh
if [ x\$CARTESI_SCRATCH != x ]; then
  mkfs.ext4 -F -F -O ^has_journal \$CARTESI_SCRATCH
  /usr/bin/mount \$CARTESI_SCRATCH /ram
else
  /bin/echo "/ram size configured as: \$CARTESI_TMPFS_SIZE"
  /usr/bin/mount -t tmpfs -o size=\$CARTESI_TMPFS_SIZE tmpfs /ram
fi
# move all to ram
/bin/echo "Moving dynamic content to tmpfs or scratch ..." 
/usr/bin/cp -ar /tmp /ram
/usr/bin/cp -ar /var /ram
/usr/bin/cp -ar /etc /ram
/usr/bin/cp -ar /opt /ram
/usr/bin/cp -ar /home /ram
/usr/bin/cp -ar /root /ram
/usr/bin/mount --bind /ram/tmp /tmp
/usr/bin/mount --bind /ram/var /var
/usr/bin/mount --bind /ram/etc /etc
/usr/bin/mount --bind /ram/opt /opt
/usr/bin/mount --bind /ram/home /home
/usr/bin/mount --bind /ram/root /root
exec /sbin/init
EOF
# /tmpfs for RWA demo backwards compatiblity
mkdir -p /ram /opt /tmpfs 
chmod +x /usr/sbin/lambada-preinit


cat > /usr/bin/yield-and-install << EOF
#!/bin/bash
       if [ ! -e /dev/cmio ]; then
               echo "No /dev/cmio"
               mkdir -p /tmp/instructions
               mount -t 9p -o trans=virtio instructions /tmp/instructions -oversion=9p2000.L
               /tmp/instructions/boot-script
               exit 0
       fi
       mkdir -p /opt/rollup-cache
       mkdir -p /opt/rollup-store
       export IO_DEVICE=/dev/pmem1
       /usr/bin/rollup-init /usr/bin/lambada-rollup-server /usr/bin/cartesi-run-app.sh

       echo "entrypoint exited with \$? status"
       dmesg
       halt -f
       exit 0
EOF
chmod +x /usr/bin/yield-and-install
cat > /etc/systemd/system/yield-and-install.service << EOF
[Unit]
Description=First yield
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/yield-and-install
RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
EOF

systemctl enable yield-and-install.service
cp /mnt/ipfs /usr/bin/ipfs
chmod a+x /usr/bin/ipfs
cp /mnt/ipfs-config /etc/ipfs-config

echo -n "root:cartesi" | chpasswd
printf "deb [check-valid-until=no] file:/mnt/mirror/snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy main restricted universe multiverse\ndeb [check-valid-until=no] file:/mnt/mirror/snapshot.ubuntu.com/ubuntu/20231201T000000Z jammy-updates main restricted universe multiverse" > /etc/apt/sources.list
apt-get update
apt-get install --no-install-recommends -y containerd curl busybox strace fuse3 jq

rm -rf /var/lib/apt/lists/*
apt-get clean
